# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 8c9ea3d3e48ba7676b48d2f8dc4a79c8014eabdb30b40f609af10216985cf4863f3895ec902727bbe6d35dad1c222a0188a3ba8f9850708a03853922e11c2ebe

test:
  secret_key_base: 42e10c87a02c54834dc05570fa1f88aa2a3429af846f7089e714763f8a7b0d05b5edf81c8276dc37dda607f11659da6cef5ae3417abf1765b469380b4c4f065c

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
